/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Report backend liveness and readiness */
    get: operations["getBackendHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate with an enabled provider */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate a refresh credential and issue a new access token */
    post: operations["refreshSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the current session */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the current application session */
    get: operations["getCurrentSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{workspaceId}/request-attachments": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: components["schemas"]["WorkspaceId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload an immutable file for request bodies */
    post: operations["uploadRequestAttachment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/executions/{executionId}/body": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    /** Download exact stored response bytes */
    get: operations["downloadExecutionResponseBody"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/plugins/catalog.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List validated frontend plugin packages */
    get: operations["listFrontendPluginCatalog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/plugins/{pluginId}/{hash}/{assetPath}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Load one asset from a content-addressed frontend plugin package */
    get: operations["getFrontendPluginAsset"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Open the frontend control connection */
    get: operations["connectBackendWebSocket"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Format: uuid */
    UuidV7: string;
    /**
     * Format: date-time
     * @description Canonical RFC 3339 UTC timestamp with millisecond precision.
     * @example 2026-07-21T09:00:00.000Z
     */
    UtcDateTime: string;
    CorrelationId: components["schemas"]["UuidV7"];
    CommandId: components["schemas"]["UuidV7"];
    EventId: components["schemas"]["UuidV7"];
    UserId: components["schemas"]["UuidV7"];
    SessionId: components["schemas"]["UuidV7"];
    WorkspaceId: components["schemas"]["UuidV7"];
    CollectionId: components["schemas"]["UuidV7"];
    EnvironmentId: components["schemas"]["UuidV7"];
    EnvironmentVariableId: components["schemas"]["UuidV7"];
    RequestId: components["schemas"]["UuidV7"];
    RevisionId: components["schemas"]["UuidV7"];
    ExecutionId: components["schemas"]["UuidV7"];
    BlobId: components["schemas"]["UuidV7"];
    RequestAttachmentId: components["schemas"]["UuidV7"];
    ProblemCode: string;
    ValidationError: {
      /** @description JSON Pointer to the invalid input. */
      path: string;
      code: components["schemas"]["ProblemCode"];
      message: string;
    };
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      code: components["schemas"]["ProblemCode"];
      detail: string;
      correlationId: components["schemas"]["CorrelationId"];
      errors: components["schemas"]["ValidationError"][];
    };
    BackendHealth: {
      /** @enum {string} */
      status: "ready" | "not_ready";
      version: string;
      /** @description Proxy API protocol version, or null when the proxy health endpoint is unavailable. */
      proxyProtocolVersion: string | null;
      checks: {
        [key: string]: "ready" | "not_ready";
      };
    };
    LoginRequest: {
      providerId: string;
      /** @description Provider-defined fields collected by the frontend. */
      fields: {
        [key: string]: string;
      };
    };
    AccessCredential: {
      accessToken: string;
      accessTokenExpiresAt: components["schemas"]["UtcDateTime"];
      session: components["schemas"]["CurrentSession"];
    };
    CurrentSession: {
      sessionId: components["schemas"]["SessionId"];
      user: components["schemas"]["CurrentUser"];
      createdAt: components["schemas"]["UtcDateTime"];
      absoluteExpiresAt: components["schemas"]["UtcDateTime"];
    };
    CurrentUser: {
      userId: components["schemas"]["UserId"];
      username: string;
      displayName: string;
    };
    WebSocketCommand:
      | components["schemas"]["SessionAuthenticateCommand"]
      | components["schemas"]["SystemPingCommand"]
      | components["schemas"]["PluginListCommand"]
      | components["schemas"]["WorkspaceListCommand"]
      | components["schemas"]["WorkspaceCreateCommand"]
      | components["schemas"]["WorkspaceGetCommand"]
      | components["schemas"]["WorkspaceUpdateCommand"]
      | components["schemas"]["WorkspaceDeleteCommand"]
      | components["schemas"]["TreeListCommand"]
      | components["schemas"]["TreeReorderCommand"]
      | components["schemas"]["TreeMoveCommand"]
      | components["schemas"]["CollectionCreateCommand"]
      | components["schemas"]["CollectionGetCommand"]
      | components["schemas"]["CollectionUpdateCommand"]
      | components["schemas"]["CollectionDeleteCommand"]
      | components["schemas"]["CollectionHeadersUpdateCommand"]
      | components["schemas"]["EnvironmentListCommand"]
      | components["schemas"]["EnvironmentCreateCommand"]
      | components["schemas"]["EnvironmentGetCommand"]
      | components["schemas"]["EnvironmentUpdateCommand"]
      | components["schemas"]["EnvironmentDeleteCommand"]
      | components["schemas"]["EnvironmentSelectCommand"]
      | components["schemas"]["EnvironmentPreviewVariablesCommand"]
      | components["schemas"]["VariableProfileGetCommand"]
      | components["schemas"]["VariableProfileGetTemporaryCommand"]
      | components["schemas"]["VariableProfileUpdateCommand"]
      | components["schemas"]["VariablePreviewCommand"]
      | components["schemas"]["ImportProvidersCommand"]
      | components["schemas"]["ImportPreviewCommand"]
      | components["schemas"]["ImportApplyCommand"]
      | components["schemas"]["RequestCreateCommand"]
      | components["schemas"]["RequestGetCommand"]
      | components["schemas"]["RequestExchangeListCommand"]
      | components["schemas"]["RequestExchangeGetCommand"]
      | components["schemas"]["RequestRevisionListCommand"]
      | components["schemas"]["RequestRevisionGetCommand"]
      | components["schemas"]["RequestRevisionNameCommand"]
      | components["schemas"]["RequestRevisionRestoreCommand"]
      | components["schemas"]["RequestDuplicateCommand"]
      | components["schemas"]["RequestUpdateCommand"]
      | components["schemas"]["RequestDeleteCommand"]
      | components["schemas"]["ExecutionStartCommand"]
      | components["schemas"]["ExecutionStartRevisionCommand"]
      | components["schemas"]["ExecutionStartTemporaryCommand"];
    CommandEnvelope: {
      /** @constant */
      protocolVersion: 1;
      /** @constant */
      kind: "command";
      id: components["schemas"]["CommandId"];
      type: string;
      payload: Record<string, never>;
    };
    SessionAuthenticateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "session.authenticate";
      payload?: {
        accessToken: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "SessionAuthenticateCommand";
    };
    SystemPingCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "system.ping";
      payload?: Record<string, never>;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "SystemPingCommand";
    };
    PluginListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "plugin.list";
      payload?: Record<string, never>;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "PluginListCommand";
    };
    WorkspaceListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.list";
      payload?: Record<string, never>;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceListCommand";
    };
    WorkspaceCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.create";
      payload?: {
        name: string;
        description?: string;
        notes?: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceCreateCommand";
    };
    WorkspaceGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.get";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceGetCommand";
    };
    WorkspaceUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.update";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        expectedRevision: number;
        name: string;
        /** @description Absolute HTTP URL template used as the root of composed request targets; blank disables composition until configured. */
        baseUrl: string;
        headers: components["schemas"]["RequestField"][];
        description?: string;
        notes?: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceUpdateCommand";
    };
    /** @description Owner-only deletion that removes the workspace from active access while retaining its immutable execution and audit history. */
    WorkspaceDeleteCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.delete";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        expectedRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceDeleteCommand";
    };
    TreeListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "tree.list";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "TreeListCommand";
    };
    TreeReorderCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "tree.reorder";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        expectedOrderRevision: number;
        orderedNodeIds: components["schemas"]["UuidV7"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "TreeReorderCommand";
    };
    TreeMoveCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "tree.move";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        nodeId: components["schemas"]["UuidV7"];
        targetNodeId: components["schemas"]["UuidV7"];
        /** @enum {string} */
        placement: "before" | "inside" | "after";
        expectedSourceOrderRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "TreeMoveCommand";
    };
    CollectionCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.create";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        name: string;
        description?: string;
        notes?: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionCreateCommand";
    };
    CollectionGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.get";
      payload?: {
        collectionId: components["schemas"]["CollectionId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionGetCommand";
    };
    CollectionUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.update";
      payload?: {
        collectionId: components["schemas"]["CollectionId"];
        expectedRevision: number;
        name: string;
        /** @description An absolute HTTP(S) URL template when this collection is the first non-empty target component, or a path template appended to an earlier component. */
        pathPrefix: string;
        headers: components["schemas"]["RequestField"][];
        description?: string;
        notes?: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionUpdateCommand";
    };
    /** @description Identifies the complete persisted subtree removed by a recursive collection deletion. */
    CollectionDeleteResult: {
      /** @constant */
      deleted: true;
      parentCollectionId: components["schemas"]["CollectionId"] | null;
      deletedCollectionIds: components["schemas"]["CollectionId"][];
      deletedRequestIds: components["schemas"]["RequestId"][];
    };
    /** @description Recursively deletes a collection, its descendant collections and requests, and their mutable profiles. Existing execution snapshots remain available. */
    CollectionDeleteCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.delete";
      payload?: {
        collectionId: components["schemas"]["CollectionId"];
        expectedRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionDeleteCommand";
    };
    CollectionHeadersUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.headers.update";
      payload?: {
        collectionId: components["schemas"]["CollectionId"];
        expectedRevision: number;
        headers: components["schemas"]["RequestField"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionHeadersUpdateCommand";
    };
    EnvironmentListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.list";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentListCommand";
    };
    EnvironmentCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.create";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        name: string;
        description?: components["schemas"]["ResourceDescription"];
        notes?: components["schemas"]["ResourceNotes"];
        variables: components["schemas"]["EnvironmentVariableWrite"][];
        /** @description Ordered included environments from lowest to highest precedence. Omission creates an environment with no includes. */
        includedEnvironmentIds?: components["schemas"]["EnvironmentId"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentCreateCommand";
    };
    EnvironmentGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.get";
      payload?: {
        environmentId: components["schemas"]["EnvironmentId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentGetCommand";
    };
    EnvironmentUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.update";
      payload?: {
        environmentId: components["schemas"]["EnvironmentId"];
        expectedRevision: number;
        name: string;
        description?: components["schemas"]["ResourceDescription"];
        notes?: components["schemas"]["ResourceNotes"];
        variables: components["schemas"]["EnvironmentVariableWrite"][];
        /** @description Complete ordered replacement from lowest to highest precedence. Omission preserves the current composition. */
        includedEnvironmentIds?: components["schemas"]["EnvironmentId"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentUpdateCommand";
    };
    EnvironmentDeleteCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.delete";
      payload?: {
        environmentId: components["schemas"]["EnvironmentId"];
        expectedRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentDeleteCommand";
    };
    EnvironmentSelectCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.select";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        environmentId: components["schemas"]["EnvironmentId"] | null;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentSelectCommand";
    };
    EnvironmentPreviewVariablesCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.preview_variables";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        names: components["schemas"]["VariableName"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentPreviewVariablesCommand";
    };
    VariableProfileGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "variable_profile.get";
      payload?: {
        scopeKind: components["schemas"]["EditableVariableScopeKind"];
        scopeId: components["schemas"]["UuidV7"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VariableProfileGetCommand";
    };
    /** @description Loads inherited variables for an unsaved request without creating persistent state. */
    VariableProfileGetTemporaryCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "variable_profile.get_temporary";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        scopeId: components["schemas"]["UuidV7"];
        scopeName: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VariableProfileGetTemporaryCommand";
    };
    VariableProfileUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "variable_profile.update";
      payload?: {
        scopeKind: components["schemas"]["EditableVariableScopeKind"];
        scopeId: components["schemas"]["UuidV7"];
        expectedRevision: number;
        variables: components["schemas"]["VariableWrite"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VariableProfileUpdateCommand";
    };
    VariablePreviewCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "variable.preview";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        requestId: components["schemas"]["RequestId"] | null;
        temporaryVariables?: components["schemas"]["TemporaryRequestVariableProfile"];
        names: components["schemas"]["VariableName"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VariablePreviewCommand";
    };
    /** @description Stable identifier of an import provider installed in the backend plugin host. */
    ImportProviderId: string;
    PluginPackageManifest: {
      /**
       * @description Plugin manifest format generation.
       * @constant
       */
      schemaVersion: 1;
      /**
       * @description Breaking-compatibility generation of the host/plugin API; package releases use SemVer separately.
       * @constant
       */
      apiVersion: 1;
      id: string;
      name: string;
      version: string;
      /** @description Higher weights are presented before lower-weight plugin contributions. */
      weight?: number;
      /** @enum {string} */
      target: "frontend" | "backend";
      entrypoint: string;
      providers: string[];
    };
    EnabledPlugin: {
      id: string;
      name: string;
      version: string;
      /** @enum {string} */
      target: "frontend" | "backend";
      /** @enum {string} */
      source: "built-in" | "user";
    };
    PluginListView: {
      plugins: components["schemas"]["EnabledPlugin"][];
    };
    FrontendPluginCatalogEntry: {
      manifest: components["schemas"]["PluginPackageManifest"];
      /** @enum {string} */
      source: "built-in" | "user";
      moduleUrl: string;
    };
    FrontendPluginCatalog: {
      plugins: components["schemas"]["FrontendPluginCatalogEntry"][];
    };
    /** @description Declarative capabilities for one installed source adapter. */
    ImportProviderManifest: {
      id: components["schemas"]["ImportProviderId"];
      version: string;
      label: string;
      acceptedExtensions: string[];
      acceptedMediaTypes: string[];
      inputKinds: "file"[];
      capabilities: {
        multipleRequests: boolean;
        hierarchy: boolean;
        attachments: boolean;
        capturedResponses: boolean;
        responseExamples: boolean;
        variables: boolean;
      };
    };
    ImportProvidersView: {
      providers: components["schemas"]["ImportProviderManifest"][];
    };
    ImportDiagnostic: {
      code: string;
      /** @enum {string} */
      severity: "info" | "warning" | "error";
      message: string;
      itemId?: string;
      itemIds?: string[];
      sourceLocation?: string;
      sourceLocations?: string[];
    };
    /** @description An imported HTTP response capture that was not executed by APInteract. */
    CapturedExchangeView: {
      capturedExchangeId?: components["schemas"]["UuidV7"];
      label?: string;
      source: components["schemas"]["ImportProviderId"];
      status: number;
      statusText: string;
      headers: components["schemas"]["HeaderField"][];
      contentType: string | null;
      body: string;
      /** @enum {string} */
      bodyEncoding: "text" | "base64";
      bodyComplete: boolean;
      bodyBytes: number;
      recordedAt: components["schemas"]["UtcDateTime"] | null;
      importedAt?: components["schemas"]["UtcDateTime"];
    };
    /** @description One provider-defined request body that may be selected before applying an import. */
    ImportedRequestBodyOption: {
      optionId: string;
      label: string;
      selectionKey?: string;
      requestBody: components["schemas"]["RequestBodyDefinition"];
      /** @description Provider-owned Markdown appended to request notes only when this option is selected. */
      documentation?: components["schemas"]["ResourceNotes"];
    };
    /** @description A provider-created collection below the imported root. */
    ImportedCollection: {
      collectionKey: string;
      parentCollectionKey: string | null;
      name: string;
      description: components["schemas"]["ResourceDescription"];
      notes: components["schemas"]["ResourceNotes"];
      pathPrefix: string;
      variables: components["schemas"]["VariableWrite"][];
    };
    ImportedRequest: {
      itemId: string;
      sourceLocation: string;
      collectionKey: string | null;
      name: string;
      description: components["schemas"]["ResourceDescription"];
      notes: components["schemas"]["ResourceNotes"];
      method: components["schemas"]["HttpMethod"];
      /** @enum {string} */
      targetMode: "absolute" | "composed";
      targetUrl: string;
      query: components["schemas"]["RequestField"][];
      headers: components["schemas"]["RequestField"][];
      requestBody: components["schemas"]["RequestBodyDefinition"];
      requestBodyOptions?: components["schemas"]["ImportedRequestBodyOption"][];
      defaultRequestBodyOptionId?: string;
      body: string;
      preRequestScript: string;
      postResponseScript: string;
      variables: components["schemas"]["VariableWrite"][];
      capturedExchange?: components["schemas"]["CapturedExchangeView"];
      capturedExchanges?: components["schemas"]["CapturedExchangeView"][];
    };
    /** @description Selects one provider-defined request body for an imported item. */
    ImportRequestBodySelection: {
      itemId: string;
      optionId: string;
    };
    /** @description A mutation-free, source-neutral preview produced by one provider. */
    ImportPlan: {
      /** @constant */
      schemaVersion: 1;
      providerId: components["schemas"]["ImportProviderId"];
      providerVersion: string;
      sourceName: string;
      sourceFingerprint: string;
      suggestedName: string;
      description: components["schemas"]["ResourceDescription"];
      notes: components["schemas"]["ResourceNotes"];
      pathPrefix: string;
      variables: components["schemas"]["VariableWrite"][];
      collections: components["schemas"]["ImportedCollection"][];
      requests: components["schemas"]["ImportedRequest"][];
      diagnostics: components["schemas"]["ImportDiagnostic"][];
    };
    ImportedCollectionResult: {
      collectionId: components["schemas"]["CollectionId"];
      parentCollectionId: components["schemas"]["CollectionId"] | null;
    };
    ImportApplyResult: {
      collectionId: components["schemas"]["CollectionId"];
      collections: components["schemas"]["ImportedCollectionResult"][];
      requests: components["schemas"]["RequestView"][];
    };
    ImportProvidersCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "import.providers";
      payload?: Record<string, never>;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "ImportProvidersCommand";
    };
    ImportPreviewCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "import.preview";
      payload?: {
        providerId: components["schemas"]["ImportProviderId"] | null;
        sourceName: string;
        sourceText: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "ImportPreviewCommand";
    };
    ImportApplyCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "import.apply";
      payload?: {
        providerId: components["schemas"]["ImportProviderId"] | null;
        sourceName: string;
        sourceText: string;
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        collectionName: string;
        selectedItemIds: string[];
        requestBodySelections?: components["schemas"]["ImportRequestBodySelection"][];
        expectedSourceFingerprint: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "ImportApplyCommand";
    };
    RequestCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.create";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        name: string;
        method: components["schemas"]["HttpMethod"];
        /** @enum {string} */
        targetMode: "absolute" | "composed";
        /** @description Absolute URL template or composed request-local path. */
        targetUrl: string;
        query: components["schemas"]["RequestField"][];
        headers: components["schemas"]["RequestField"][];
        body: string;
        requestBody?: components["schemas"]["RequestBodyDefinition"];
        preRequestScript?: string;
        postResponseScript?: string;
        variables?: components["schemas"]["VariableWrite"][];
        description?: string;
        notes?: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestCreateCommand";
    };
    RequestGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.get";
      payload?: {
        requestId: components["schemas"]["RequestId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestGetCommand";
    };
    /** @description Lists persisted executions and imported captures owned by one request. */
    RequestExchangeListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.exchange.list";
      payload?: {
        requestId: components["schemas"]["RequestId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestExchangeListCommand";
    };
    /** @description Loads one selected immutable request-response exchange. */
    RequestExchangeGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.exchange.get";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        exchangeId: components["schemas"]["UuidV7"];
        /** @enum {string} */
        kind: "execution" | "capture";
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestExchangeGetCommand";
    };
    /** @description Creates an adjacent request with a fresh draft and cloned request-scoped variables, excluding execution and revision history. */
    RequestDuplicateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.duplicate";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        name: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestDuplicateCommand";
    };
    RequestRevisionListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.revision.list";
      payload?: {
        requestId: components["schemas"]["RequestId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestRevisionListCommand";
    };
    RequestRevisionGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.revision.get";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        revisionId: components["schemas"]["RevisionId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestRevisionGetCommand";
    };
    RequestRevisionNameCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.revision.name";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        revisionId: components["schemas"]["RevisionId"];
        name: string | null;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestRevisionNameCommand";
    };
    RequestRevisionRestoreCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.revision.restore";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        revisionId: components["schemas"]["RevisionId"];
        expectedDraftRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestRevisionRestoreCommand";
    };
    RequestUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.update";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        expectedDraftRevision: number;
        name: string;
        method: components["schemas"]["HttpMethod"];
        /** @enum {string} */
        targetMode: "absolute" | "composed";
        /** @description Absolute URL template or composed request-local path. */
        targetUrl: string;
        query: components["schemas"]["RequestField"][];
        headers: components["schemas"]["RequestField"][];
        body: string;
        requestBody?: components["schemas"]["RequestBodyDefinition"];
        preRequestScript?: string;
        postResponseScript?: string;
        variableProfile?: components["schemas"]["RequestVariableProfileUpdate"];
        description?: string;
        notes?: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestUpdateCommand";
    };
    /** @description Deletes a mutable saved request and its variable profile after detaching any durable execution snapshots. */
    RequestDeleteCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.delete";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        expectedDraftRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestDeleteCommand";
    };
    ExecutionStartCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "execution.start";
      payload?: {
        requestId: components["schemas"]["RequestId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "ExecutionStartCommand";
    };
    ExecutionStartRevisionCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "execution.start_revision";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        revisionId: components["schemas"]["RevisionId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "ExecutionStartRevisionCommand";
    };
    ExecutionStartTemporaryCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "execution.start_temporary";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        request: components["schemas"]["RequestExecutionInput"];
        temporaryVariables?: components["schemas"]["TemporaryRequestVariableProfile"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "ExecutionStartTemporaryCommand";
    };
    WebSocketReply: {
      /** @constant */
      protocolVersion: 1;
      /** @constant */
      kind: "reply";
      commandId: components["schemas"]["CommandId"];
      /** @enum {string} */
      outcome: "success" | "error";
      correlationId: components["schemas"]["CorrelationId"];
      payload?: components["schemas"]["WebSocketReplyPayload"];
      error?: components["schemas"]["WebSocketError"];
    };
    WebSocketReplyPayload:
      | components["schemas"]["WorkspaceView"]
      | components["schemas"]["EnvironmentListView"]
      | components["schemas"]["EnvironmentView"]
      | components["schemas"]["VariableProfileView"]
      | components["schemas"]["VariablePreviewResult"]
      | components["schemas"]["CollectionDeleteResult"]
      | components["schemas"]["ImportProvidersView"]
      | components["schemas"]["PluginListView"]
      | components["schemas"]["ImportPlan"]
      | components["schemas"]["ImportApplyResult"]
      | components["schemas"]["RequestExchangeListView"]
      | components["schemas"]["RequestExchangeView"]
      | {
          [key: string]: unknown;
        };
    WebSocketError: {
      code: components["schemas"]["ProblemCode"];
      message: string;
      errors: components["schemas"]["ValidationError"][];
    };
    WebSocketEvent: {
      /** @constant */
      protocolVersion: 1;
      /** @constant */
      kind: "event";
      id: components["schemas"]["EventId"];
      type: string;
      occurredAt: components["schemas"]["UtcDateTime"];
      correlationId: components["schemas"]["CorrelationId"];
      payload: unknown;
    };
    WorkspaceSummary: {
      workspaceId: components["schemas"]["WorkspaceId"];
      name: string;
      /** @enum {string} */
      role: "owner" | "editor" | "viewer";
    };
    WorkspaceView: {
      workspaceId: components["schemas"]["WorkspaceId"];
      name: string;
      /** @enum {string} */
      role: "owner" | "editor" | "viewer";
      description: components["schemas"]["ResourceDescription"];
      notes: components["schemas"]["ResourceNotes"];
      baseUrl: string;
      headers: components["schemas"]["RequestField"][];
      revision: number;
    };
    TreeNode: {
      nodeId: components["schemas"]["UuidV7"];
      /** @enum {string} */
      kind: "collection" | "request";
      name: string;
      position: number;
      /** @description Optimistic concurrency revision shared by this sibling list. */
      orderRevision: number;
      method?: components["schemas"]["HttpMethod"];
    };
    EnvironmentSummary: {
      environmentId: components["schemas"]["EnvironmentId"];
      name: string;
      revision: number;
    };
    EnvironmentListView: {
      environments: components["schemas"]["EnvironmentSummary"][];
      selectedEnvironmentId: components["schemas"]["EnvironmentId"] | null;
    };
    VariablePreviewResult: {
      previews: components["schemas"]["VariablePreview"][];
    };
    VariablePreview: {
      name: components["schemas"]["VariableName"];
      /** @enum {string} */
      status: "resolved" | "missing" | "unset" | "error";
      declaredKind: ("value" | "secret" | "alias" | "unset") | null;
      effectiveKind: ("value" | "secret") | null;
      aliasTarget: components["schemas"]["VariableName"] | null;
      /** @description Resolved ordinary value. Secret-derived and unresolved values are always null. */
      value: string | null;
      secretVersion: number | null;
      diagnostic: string | null;
      source: components["schemas"]["VariablePreviewSource"] | null;
    };
    VariablePreviewSource: {
      /** @enum {string} */
      scope: "workspace" | "collection" | "environment" | "request";
      scopeId: components["schemas"]["UuidV7"];
      scopeName: string;
      revision: number;
    };
    /** @enum {string} */
    EditableVariableScopeKind: "workspace" | "collection" | "request";
    VariableView: components["schemas"]["EnvironmentVariableView"];
    InheritedVariableView: {
      variable: components["schemas"]["VariableView"];
      source: components["schemas"]["VariablePreviewSource"];
    };
    VariableWrite: components["schemas"]["EnvironmentVariableWrite"];
    /** @description An unsaved request's highest-precedence variable layer. */
    TemporaryRequestVariableProfile: {
      scopeId: components["schemas"]["UuidV7"];
      scopeName: string;
      variables: components["schemas"]["VariableWrite"][];
    };
    /** @description Optional request-variable mutation committed atomically with request draft updates. */
    RequestVariableProfileUpdate: {
      expectedRevision: number;
      variables: components["schemas"]["VariableWrite"][];
    };
    VariableProfileView: {
      workspaceId: components["schemas"]["WorkspaceId"];
      scopeKind: components["schemas"]["EditableVariableScopeKind"];
      scopeId: components["schemas"]["UuidV7"];
      scopeName: string;
      revision: number;
      variables: components["schemas"]["VariableView"][];
      /** @description Effective lower-precedence variables before this scope applies its local declarations. */
      inheritedVariables: components["schemas"]["InheritedVariableView"][];
    };
    EnvironmentVariableView:
      | components["schemas"]["EnvironmentValueVariableView"]
      | components["schemas"]["EnvironmentSecretVariableView"]
      | components["schemas"]["EnvironmentAliasVariableView"]
      | components["schemas"]["EnvironmentUnsetVariableView"];
    EnvironmentValueVariableView: {
      variableId: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      description: components["schemas"]["FieldDescription"];
      /** @constant */
      kind: "value";
      value: string;
    };
    EnvironmentSecretVariableView: {
      variableId: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      description: components["schemas"]["FieldDescription"];
      /** @constant */
      kind: "secret";
      hasValue: boolean;
      secretVersion: number;
    };
    EnvironmentAliasVariableView: {
      variableId: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      description: components["schemas"]["FieldDescription"];
      /** @constant */
      kind: "alias";
      target: components["schemas"]["VariableName"];
    };
    EnvironmentUnsetVariableView: {
      variableId: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      description: components["schemas"]["FieldDescription"];
      /** @constant */
      kind: "unset";
    };
    /** @description Creates a variable when variableId is omitted or updates the identified variable without changing its existing kind. */
    EnvironmentVariableWrite:
      | components["schemas"]["EnvironmentValueVariableWrite"]
      | components["schemas"]["EnvironmentSecretVariableWrite"]
      | components["schemas"]["EnvironmentAliasVariableWrite"]
      | components["schemas"]["EnvironmentUnsetVariableWrite"];
    EnvironmentValueVariableWrite: {
      variableId?: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      description?: components["schemas"]["FieldDescription"];
      /** @constant */
      kind: "value";
      value: string;
    };
    EnvironmentSecretVariableWrite: {
      variableId?: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      description?: components["schemas"]["FieldDescription"];
      /** @constant */
      kind: "secret";
      value?: string;
      clearValue?: boolean;
    };
    EnvironmentAliasVariableWrite: {
      variableId?: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      description?: components["schemas"]["FieldDescription"];
      /** @constant */
      kind: "alias";
      target: components["schemas"]["VariableName"];
    };
    EnvironmentUnsetVariableWrite: {
      variableId?: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      description?: components["schemas"]["FieldDescription"];
      /** @constant */
      kind: "unset";
    };
    VariableName: string;
    FieldDescription: string;
    ResourceDescription: string;
    ResourceNotes: string;
    EnvironmentView: {
      environmentId: components["schemas"]["EnvironmentId"];
      workspaceId: components["schemas"]["WorkspaceId"];
      name: string;
      description: components["schemas"]["ResourceDescription"];
      notes: components["schemas"]["ResourceNotes"];
      revision: number;
      /** @description Directly included environments in low-to-high precedence order. */
      includedEnvironments: components["schemas"]["EnvironmentSummary"][];
      variables: components["schemas"]["EnvironmentVariableView"][];
      /** @description Effective workspace and included-environment variables before this environment applies its local declarations. */
      inheritedVariables: components["schemas"]["InheritedVariableView"][];
    };
    CollectionView: {
      collectionId: components["schemas"]["CollectionId"];
      workspaceId: components["schemas"]["WorkspaceId"];
      parentCollectionId: components["schemas"]["CollectionId"] | null;
      name: string;
      description: components["schemas"]["ResourceDescription"];
      notes: components["schemas"]["ResourceNotes"];
      /** @description An absolute HTTP(S) URL template when this collection is the first non-empty target component, or a path template appended to an earlier component. */
      pathPrefix: string;
      /** @description Current composed workspace and ancestor-collection target prefix before this collection's local component. */
      inheritedTarget: string;
      /** @description Root-to-current collection target prefix. It may include an absolute URL established by the first non-empty collection component. */
      effectivePath: string;
      headers: components["schemas"]["RequestField"][];
      /** @description Effective enabled headers inherited from the workspace and ancestor collections before this collection's local overrides. */
      inheritedHeaders: components["schemas"]["RequestField"][];
      /** @description Effective enabled headers after applying ancestor and local collection profiles. */
      effectiveHeaders: components["schemas"]["RequestField"][];
      revision: number;
    };
    /** @description Editable request body semantics before interpolation or attachment byte retrieval. */
    RequestBodyDefinition:
      | components["schemas"]["NoRequestBody"]
      | components["schemas"]["TextRequestBody"]
      | components["schemas"]["FileRequestBody"]
      | components["schemas"]["UrlEncodedRequestBody"]
      | components["schemas"]["MultipartRequestBody"];
    NoRequestBody: {
      /** @constant */
      kind: "none";
    };
    TextRequestBody: {
      /** @constant */
      kind: "text";
      /** @description Optional body-owned media type applied as the effective Content-Type during execution. */
      contentType: string | null;
      text: string;
    };
    /** @description An immutable uploaded file used as the complete binary request body. */
    FileRequestBody: {
      /** @constant */
      kind: "file";
      /** @description Optional media type override; the attachment media type is used by default. */
      contentType: string | null;
      attachment: components["schemas"]["RequestAttachment"];
    };
    /** @description Ordered text fields encoded as application/x-www-form-urlencoded after interpolation. */
    UrlEncodedRequestBody: {
      /** @constant */
      kind: "urlencoded";
      contentType: string | null;
      fields: components["schemas"]["RequestField"][];
    };
    /** @description Ordered multipart/form-data text fields and immutable file attachments. */
    MultipartRequestBody: {
      /** @constant */
      kind: "multipart";
      /** @description Optional media type override without a boundary parameter; the persisted boundary is appended during execution. */
      contentType: string | null;
      boundary: string;
      fields: (
        | components["schemas"]["RequestField"]
        | components["schemas"]["MultipartFileField"]
      )[];
    };
    /** @description Immutable workspace-owned upload metadata referenced by request bodies or multipart file fields. */
    RequestAttachment: {
      attachmentId: components["schemas"]["RequestAttachmentId"];
      workspaceId: components["schemas"]["WorkspaceId"];
      fileName: string;
      contentType: string;
      byteLength: number;
      sha256: string;
    };
    /** @description One uploaded file positioned among multipart text fields. */
    MultipartFileField: {
      /** @constant */
      kind: "file";
      name: string;
      enabled: boolean;
      description?: string;
      attachment: components["schemas"]["RequestAttachment"];
    };
    RequestView: {
      requestId: components["schemas"]["RequestId"];
      workspaceId: components["schemas"]["WorkspaceId"];
      parentCollectionId: components["schemas"]["CollectionId"] | null;
      name: string;
      description: components["schemas"]["ResourceDescription"];
      notes: components["schemas"]["ResourceNotes"];
      method: components["schemas"]["HttpMethod"];
      /** @enum {string} */
      targetMode: "absolute" | "composed";
      /** @description Absolute URL template in absolute mode, or a path-only template in composed mode. */
      targetUrl: string;
      /** @description Current composed workspace and collection target prefix before the request-local path. */
      inheritedTarget: string;
      /** @constant */
      queryMode: "structured";
      query: components["schemas"]["RequestField"][];
      headers: components["schemas"]["RequestField"][];
      /** @description Effective enabled headers inherited from the request's collection ancestry before request-local overrides. */
      inheritedHeaders: components["schemas"]["RequestField"][];
      body: string;
      /** @description Preferred semantic body definition. Older responses may omit it, in which case clients use the legacy body projection. */
      requestBody?: components["schemas"]["RequestBodyDefinition"];
      preRequestScript: string;
      postResponseScript: string;
      capturedExchange?: components["schemas"]["CapturedExchangeView"];
      draftRevision: number;
    };
    RequestRevisionSummary: {
      revisionId: components["schemas"]["RevisionId"];
      requestId: components["schemas"]["RequestId"];
      name: string | null;
      /** @enum {string} */
      creationReason: "manual_save" | "execution";
      createdBy: components["schemas"]["UserId"];
      createdByUsername: string;
      createdAt: components["schemas"]["UtcDateTime"];
    };
    RequestRevisionView: components["schemas"]["RequestRevisionSummary"] & {
      request: components["schemas"]["RequestView"];
    };
    /** @description Compact metadata for one persisted request-response record. */
    RequestExchangeSummary: {
      exchangeId: components["schemas"]["UuidV7"];
      requestId: components["schemas"]["RequestId"];
      requestRevisionId: components["schemas"]["UuidV7"] | null;
      /** @enum {string} */
      kind: "execution" | "capture";
      /** @description APInteract for executions, otherwise the import-provider ID that supplied the capture. */
      source: string;
      /** @description Optional provider-defined label for an imported capture. */
      label?: string;
      /** @enum {string} */
      state: "created" | "running" | "completed" | "failed";
      status?: number;
      /** @enum {string} */
      bodyAvailability: "complete" | "truncated" | "unavailable";
      occurredAt: components["schemas"]["UtcDateTime"];
    };
    RequestExchangeListView: {
      exchanges: components["schemas"]["RequestExchangeSummary"][];
    };
    /** @description One selected exchange projected for immutable response display. */
    RequestExchangeView: {
      summary: components["schemas"]["RequestExchangeSummary"];
      execution: components["schemas"]["ExecutionView"];
    };
    ExecutionView: {
      executionId: components["schemas"]["ExecutionId"];
      requestId?: components["schemas"]["RequestId"];
      /** @enum {string} */
      state: "created" | "running" | "completed" | "failed";
      status?: number;
      headers?: components["schemas"]["HeaderField"][];
      bodyComplete: boolean;
      bodyBytes?: number;
      bodySha256?: string;
      bodyPreview?: string;
      bodyBlobId?: components["schemas"]["BlobId"];
      createdAt: components["schemas"]["UtcDateTime"];
      completedAt?: components["schemas"]["UtcDateTime"];
      error?: components["schemas"]["WebSocketError"];
      scriptLogs: components["schemas"]["ScriptLogEntry"][];
      scriptTests: components["schemas"]["ScriptTestResult"][];
      /** @description Value-free receipts for persistent variable writes committed with this execution. */
      scriptVariableWrites?: components["schemas"]["ScriptVariableWriteResult"][];
      scriptError?: components["schemas"]["ScriptPhaseError"];
      outgoingRequest?: components["schemas"]["OutgoingRequestView"];
    };
    /** @description Secret-redacted representation of the materialized request handed to the proxy. It is absent when execution fails before proxy dispatch. */
    OutgoingRequestView: {
      method: components["schemas"]["HttpMethod"];
      url: components["schemas"]["InspectableRequestValue"];
      headers: components["schemas"]["InspectableRequestHeader"][];
      body: components["schemas"]["InspectableRequestBody"];
    };
    InspectableRequestValue: {
      value: string;
      redacted: boolean;
    };
    InspectableRequestHeader: {
      name: string;
      value: string;
      redacted: boolean;
      /** @description Whether the value is simulated from final transport semantics rather than supplied as a proxy header field. */
      derived: boolean;
    };
    InspectableRequestBody: {
      value: string;
      /** @enum {string} */
      encoding: "utf8" | "base64";
      byteLength: number;
      redacted: boolean;
      /** @description Whether the displayed value is only a bounded prefix of the outgoing body. */
      truncated: boolean;
    };
    HeaderField: {
      name: string;
      value: string;
    };
    RequestExecutionInput: {
      method: components["schemas"]["HttpMethod"];
      /** @enum {string} */
      targetMode: "absolute" | "composed";
      /** @description Absolute URL template or composed request-local path. */
      targetUrl: string;
      query: components["schemas"]["RequestField"][];
      headers: components["schemas"]["RequestField"][];
      body: string;
      requestBody?: components["schemas"]["RequestBodyDefinition"];
      preRequestScript?: string;
      postResponseScript?: string;
    };
    ScriptLogEntry: {
      /** @description One-based production order across script logs and tests for this execution. */
      sequence: number;
      /** @enum {string} */
      phase: "pre-request" | "post-response";
      /** @enum {string} */
      level: "debug" | "info" | "warn" | "error";
      message: string;
      fields?: {
        [key: string]: string | number | boolean | null;
      };
    };
    ScriptTestResult: {
      /** @description One-based production order across script logs and tests for this execution. */
      sequence: number;
      name: string;
      /** @enum {string} */
      status: "passed" | "failed" | "errored";
      message?: string;
      /** @description Stable SDK/runtime code or JavaScript error name, when available. */
      code?: string;
      /** @description One-based source line reported for the test body failure. */
      line?: number;
      /** @description One-based source column reported for the test body failure. */
      column?: number;
      /**
       * @description Stable localization key for an SDK-generated test message. Omitted for script-authored messages.
       * @enum {string}
       */
      messageCode?:
        | "assertion_expected_truthy"
        | "assertion_values_not_equal"
        | "assertion_values_not_deeply_equal"
        | "assertion_value_does_not_match"
        | "test_threw_non_error";
    };
    /** @description Identifies one persistent variable write without exposing its value. */
    ScriptVariableWriteResult: {
      name: components["schemas"]["VariableName"];
      /** @enum {string} */
      scope:
        | "request"
        | "parent-collection"
        | "workspace"
        | "selected-environment";
      /** @enum {string} */
      kind: "value" | "secret";
    };
    ScriptPhaseError: {
      /** @enum {string} */
      phase: "pre-request" | "post-response";
      code: string;
      message: string;
      line?: number;
      column?: number;
    };
    /** @enum {string} */
    HttpMethod:
      | "GET"
      | "POST"
      | "PUT"
      | "PATCH"
      | "DELETE"
      | "HEAD"
      | "OPTIONS";
    RequestField: {
      name: string;
      value: string;
      enabled: boolean;
      description?: components["schemas"]["FieldDescription"];
      /**
       * @description Whether this header-value pair replaces same-name values from older scopes or appends to them.
       * @enum {string}
       */
      mode?: "override" | "append";
    };
  };
  responses: {
    /** @description The request is invalid. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description Authentication is required or failed. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The current user is not allowed to perform this operation. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The requested resource does not exist or is not visible. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    ExecutionId: components["schemas"]["ExecutionId"];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getBackendHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backend health state. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackendHealth"];
        };
      };
      /** @description Backend is not ready; the response includes component versions and dependency checks. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackendHealth"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Authentication succeeded and a refresh cookie was set. */
      200: {
        headers: {
          /** @description Opaque rotating refresh credential in an HttpOnly cookie. */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessCredential"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
    };
  };
  refreshSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Refresh succeeded and the refresh cookie was rotated. */
      200: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessCredential"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked and refresh cookie cleared. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getCurrentSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current session. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentSession"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  uploadRequestAttachment: {
    parameters: {
      query?: never;
      header: {
        /** @description Percent-encoded UTF-8 filename. */
        "X-APInteract-File-Name": string;
        /** @description Percent-encoded MIME type; defaults to application/octet-stream. */
        "X-APInteract-File-Type"?: string;
      };
      path: {
        workspaceId: components["schemas"]["WorkspaceId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": string;
      };
    };
    responses: {
      /** @description Immutable workspace attachment metadata. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RequestAttachment"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
      /** @description The attachment exceeds the request-body limit. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  downloadExecutionResponseBody: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exact response body bytes. */
      200: {
        headers: {
          "Content-Length"?: number;
          Digest?: string;
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  listFrontendPluginCatalog: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Content-addressed frontend plugin catalog. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FrontendPluginCatalog"];
        };
      };
    };
  };
  getFrontendPluginAsset: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pluginId: string;
        hash: string;
        /** @description Package-relative path below dist/. Runtime routing accepts nested path segments. */
        assetPath: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Immutable package asset with a media type selected from its extension. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  connectBackendWebSocket: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket protocol upgrade. */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
