/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Report backend liveness and readiness */
    get: operations["getBackendHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate with an enabled provider */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate a refresh credential and issue a new access token */
    post: operations["refreshSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the current session */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the current application session */
    get: operations["getCurrentSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/executions/{executionId}/body": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    /** Download exact stored response bytes */
    get: operations["downloadExecutionResponseBody"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Open the frontend control connection */
    get: operations["connectBackendWebSocket"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Format: uuid */
    UuidV7: string;
    /**
     * Format: date-time
     * @description Canonical RFC 3339 UTC timestamp with millisecond precision.
     * @example 2026-07-21T09:00:00.000Z
     */
    UtcDateTime: string;
    CorrelationId: components["schemas"]["UuidV7"];
    CommandId: components["schemas"]["UuidV7"];
    EventId: components["schemas"]["UuidV7"];
    UserId: components["schemas"]["UuidV7"];
    SessionId: components["schemas"]["UuidV7"];
    WorkspaceId: components["schemas"]["UuidV7"];
    CollectionId: components["schemas"]["UuidV7"];
    EnvironmentId: components["schemas"]["UuidV7"];
    EnvironmentVariableId: components["schemas"]["UuidV7"];
    RequestId: components["schemas"]["UuidV7"];
    ExecutionId: components["schemas"]["UuidV7"];
    BlobId: components["schemas"]["UuidV7"];
    ProblemCode: string;
    ValidationError: {
      /** @description JSON Pointer to the invalid input. */
      path: string;
      code: components["schemas"]["ProblemCode"];
      message: string;
    };
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      code: components["schemas"]["ProblemCode"];
      detail: string;
      correlationId: components["schemas"]["CorrelationId"];
      errors: components["schemas"]["ValidationError"][];
    };
    BackendHealth: {
      /** @enum {string} */
      status: "ready" | "not_ready";
      version: string;
      checks: {
        [key: string]: "ready" | "not_ready";
      };
    };
    LoginRequest: {
      providerId: string;
      /** @description Provider-defined fields collected by the frontend. */
      fields: {
        [key: string]: string;
      };
    };
    AccessCredential: {
      accessToken: string;
      accessTokenExpiresAt: components["schemas"]["UtcDateTime"];
      session: components["schemas"]["CurrentSession"];
    };
    CurrentSession: {
      sessionId: components["schemas"]["SessionId"];
      user: components["schemas"]["CurrentUser"];
      createdAt: components["schemas"]["UtcDateTime"];
      absoluteExpiresAt: components["schemas"]["UtcDateTime"];
    };
    CurrentUser: {
      userId: components["schemas"]["UserId"];
      username: string;
      displayName: string;
    };
    WebSocketCommand:
      | components["schemas"]["SessionAuthenticateCommand"]
      | components["schemas"]["SystemPingCommand"]
      | components["schemas"]["WorkspaceListCommand"]
      | components["schemas"]["WorkspaceCreateCommand"]
      | components["schemas"]["WorkspaceGetCommand"]
      | components["schemas"]["WorkspaceUpdateCommand"]
      | components["schemas"]["WorkspaceDeleteCommand"]
      | components["schemas"]["TreeListCommand"]
      | components["schemas"]["TreeReorderCommand"]
      | components["schemas"]["TreeMoveCommand"]
      | components["schemas"]["CollectionCreateCommand"]
      | components["schemas"]["CollectionGetCommand"]
      | components["schemas"]["CollectionUpdateCommand"]
      | components["schemas"]["CollectionDeleteCommand"]
      | components["schemas"]["CollectionHeadersUpdateCommand"]
      | components["schemas"]["EnvironmentListCommand"]
      | components["schemas"]["EnvironmentCreateCommand"]
      | components["schemas"]["EnvironmentGetCommand"]
      | components["schemas"]["EnvironmentUpdateCommand"]
      | components["schemas"]["EnvironmentDeleteCommand"]
      | components["schemas"]["EnvironmentSelectCommand"]
      | components["schemas"]["EnvironmentPreviewVariablesCommand"]
      | components["schemas"]["VariableProfileGetCommand"]
      | components["schemas"]["VariableProfileUpdateCommand"]
      | components["schemas"]["VariablePreviewCommand"]
      | components["schemas"]["RequestCreateCommand"]
      | components["schemas"]["RequestGetCommand"]
      | components["schemas"]["RequestDuplicateCommand"]
      | components["schemas"]["RequestUpdateCommand"]
      | components["schemas"]["RequestDeleteCommand"]
      | components["schemas"]["ExecutionStartCommand"]
      | components["schemas"]["ExecutionStartTemporaryCommand"];
    CommandEnvelope: {
      /** @constant */
      protocolVersion: 1;
      /** @constant */
      kind: "command";
      id: components["schemas"]["CommandId"];
      type: string;
      payload: Record<string, never>;
    };
    SessionAuthenticateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "session.authenticate";
      payload?: {
        accessToken: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "SessionAuthenticateCommand";
    };
    SystemPingCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "system.ping";
      payload?: Record<string, never>;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "SystemPingCommand";
    };
    WorkspaceListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.list";
      payload?: Record<string, never>;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceListCommand";
    };
    WorkspaceCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.create";
      payload?: {
        name: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceCreateCommand";
    };
    WorkspaceGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.get";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceGetCommand";
    };
    WorkspaceUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.update";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        expectedRevision: number;
        name: string;
        headers: components["schemas"]["RequestField"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceUpdateCommand";
    };
    /** @description Owner-only deletion that removes the workspace from active access while retaining its immutable execution and audit history. */
    WorkspaceDeleteCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.delete";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        expectedRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceDeleteCommand";
    };
    TreeListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "tree.list";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "TreeListCommand";
    };
    TreeReorderCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "tree.reorder";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        expectedOrderRevision: number;
        orderedNodeIds: components["schemas"]["UuidV7"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "TreeReorderCommand";
    };
    TreeMoveCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "tree.move";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        nodeId: components["schemas"]["UuidV7"];
        targetNodeId: components["schemas"]["UuidV7"];
        /** @enum {string} */
        placement: "before" | "inside" | "after";
        expectedSourceOrderRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "TreeMoveCommand";
    };
    CollectionCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.create";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        name: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionCreateCommand";
    };
    CollectionGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.get";
      payload?: {
        collectionId: components["schemas"]["CollectionId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionGetCommand";
    };
    CollectionUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.update";
      payload?: {
        collectionId: components["schemas"]["CollectionId"];
        expectedRevision: number;
        name: string;
        headers: components["schemas"]["RequestField"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionUpdateCommand";
    };
    /** @description Recursively deletes a collection, its descendant collections and requests, and their mutable profiles. Existing execution snapshots remain available. */
    CollectionDeleteCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.delete";
      payload?: {
        collectionId: components["schemas"]["CollectionId"];
        expectedRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionDeleteCommand";
    };
    CollectionHeadersUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.headers.update";
      payload?: {
        collectionId: components["schemas"]["CollectionId"];
        expectedRevision: number;
        headers: components["schemas"]["RequestField"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionHeadersUpdateCommand";
    };
    EnvironmentListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.list";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentListCommand";
    };
    EnvironmentCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.create";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        name: string;
        variables: components["schemas"]["EnvironmentVariableWrite"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentCreateCommand";
    };
    EnvironmentGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.get";
      payload?: {
        environmentId: components["schemas"]["EnvironmentId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentGetCommand";
    };
    EnvironmentUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.update";
      payload?: {
        environmentId: components["schemas"]["EnvironmentId"];
        expectedRevision: number;
        name: string;
        variables: components["schemas"]["EnvironmentVariableWrite"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentUpdateCommand";
    };
    EnvironmentDeleteCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.delete";
      payload?: {
        environmentId: components["schemas"]["EnvironmentId"];
        expectedRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentDeleteCommand";
    };
    EnvironmentSelectCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.select";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        environmentId: components["schemas"]["EnvironmentId"] | null;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentSelectCommand";
    };
    EnvironmentPreviewVariablesCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "environment.preview_variables";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        names: components["schemas"]["VariableName"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "EnvironmentPreviewVariablesCommand";
    };
    VariableProfileGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "variable_profile.get";
      payload?: {
        scopeKind: components["schemas"]["EditableVariableScopeKind"];
        scopeId: components["schemas"]["UuidV7"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VariableProfileGetCommand";
    };
    VariableProfileUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "variable_profile.update";
      payload?: {
        scopeKind: components["schemas"]["EditableVariableScopeKind"];
        scopeId: components["schemas"]["UuidV7"];
        expectedRevision: number;
        variables: components["schemas"]["VariableWrite"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VariableProfileUpdateCommand";
    };
    VariablePreviewCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "variable.preview";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        requestId: components["schemas"]["RequestId"] | null;
        names: components["schemas"]["VariableName"][];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "VariablePreviewCommand";
    };
    RequestCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.create";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        name: string;
        method: components["schemas"]["HttpMethod"];
        /** @description Absolute HTTP URL template validated after variable interpolation. */
        targetUrl: string;
        query: components["schemas"]["RequestField"][];
        headers: components["schemas"]["RequestField"][];
        body: string;
        preRequestScript?: string;
        postResponseScript?: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestCreateCommand";
    };
    RequestGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.get";
      payload?: {
        requestId: components["schemas"]["RequestId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestGetCommand";
    };
    /** @description Creates an adjacent request with a fresh draft and cloned request-scoped variables, excluding execution and revision history. */
    RequestDuplicateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.duplicate";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        name: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestDuplicateCommand";
    };
    RequestUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.update";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        expectedDraftRevision: number;
        name: string;
        method: components["schemas"]["HttpMethod"];
        /** @description Absolute HTTP URL template validated after variable interpolation. */
        targetUrl: string;
        query: components["schemas"]["RequestField"][];
        headers: components["schemas"]["RequestField"][];
        body: string;
        preRequestScript?: string;
        postResponseScript?: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestUpdateCommand";
    };
    /** @description Deletes a mutable saved request and its variable profile after detaching any durable execution snapshots. */
    RequestDeleteCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.delete";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        expectedDraftRevision: number;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestDeleteCommand";
    };
    ExecutionStartCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "execution.start";
      payload?: {
        requestId: components["schemas"]["RequestId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "ExecutionStartCommand";
    };
    ExecutionStartTemporaryCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "execution.start_temporary";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        request: components["schemas"]["RequestExecutionInput"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "ExecutionStartTemporaryCommand";
    };
    WebSocketReply: {
      /** @constant */
      protocolVersion: 1;
      /** @constant */
      kind: "reply";
      commandId: components["schemas"]["CommandId"];
      /** @enum {string} */
      outcome: "success" | "error";
      correlationId: components["schemas"]["CorrelationId"];
      payload?: components["schemas"]["WebSocketReplyPayload"];
      error?: components["schemas"]["WebSocketError"];
    };
    WebSocketReplyPayload:
      | components["schemas"]["WorkspaceView"]
      | components["schemas"]["EnvironmentListView"]
      | components["schemas"]["EnvironmentView"]
      | components["schemas"]["VariableProfileView"]
      | components["schemas"]["VariablePreviewResult"]
      | {
          [key: string]: unknown;
        };
    WebSocketError: {
      code: components["schemas"]["ProblemCode"];
      message: string;
      errors: components["schemas"]["ValidationError"][];
    };
    WebSocketEvent: {
      /** @constant */
      protocolVersion: 1;
      /** @constant */
      kind: "event";
      id: components["schemas"]["EventId"];
      type: string;
      occurredAt: components["schemas"]["UtcDateTime"];
      correlationId: components["schemas"]["CorrelationId"];
      payload: unknown;
    };
    WorkspaceSummary: {
      workspaceId: components["schemas"]["WorkspaceId"];
      name: string;
      /** @enum {string} */
      role: "owner" | "editor" | "viewer";
    };
    WorkspaceView: {
      workspaceId: components["schemas"]["WorkspaceId"];
      name: string;
      /** @enum {string} */
      role: "owner" | "editor" | "viewer";
      headers: components["schemas"]["RequestField"][];
      revision: number;
    };
    TreeNode: {
      nodeId: components["schemas"]["UuidV7"];
      /** @enum {string} */
      kind: "collection" | "request";
      name: string;
      position: number;
      /** @description Optimistic concurrency revision shared by this sibling list. */
      orderRevision: number;
      method?: components["schemas"]["HttpMethod"];
    };
    EnvironmentSummary: {
      environmentId: components["schemas"]["EnvironmentId"];
      name: string;
      revision: number;
    };
    EnvironmentListView: {
      environments: components["schemas"]["EnvironmentSummary"][];
      selectedEnvironmentId: components["schemas"]["EnvironmentId"] | null;
    };
    VariablePreviewResult: {
      previews: components["schemas"]["VariablePreview"][];
    };
    VariablePreview: {
      name: components["schemas"]["VariableName"];
      /** @enum {string} */
      status: "resolved" | "missing" | "unset" | "error";
      declaredKind: ("value" | "secret" | "alias" | "unset") | null;
      effectiveKind: ("value" | "secret") | null;
      aliasTarget: components["schemas"]["VariableName"] | null;
      /** @description Resolved ordinary value. Secret-derived and unresolved values are always null. */
      value: string | null;
      secretVersion: number | null;
      diagnostic: string | null;
      source: components["schemas"]["VariablePreviewSource"] | null;
    };
    VariablePreviewSource: {
      /** @enum {string} */
      scope: "workspace" | "collection" | "environment" | "request";
      scopeId: components["schemas"]["UuidV7"];
      scopeName: string;
      revision: number;
    };
    /** @enum {string} */
    EditableVariableScopeKind: "workspace" | "collection" | "request";
    VariableView: components["schemas"]["EnvironmentVariableView"];
    VariableWrite: components["schemas"]["EnvironmentVariableWrite"];
    VariableProfileView: {
      workspaceId: components["schemas"]["WorkspaceId"];
      scopeKind: components["schemas"]["EditableVariableScopeKind"];
      scopeId: components["schemas"]["UuidV7"];
      scopeName: string;
      revision: number;
      variables: components["schemas"]["VariableView"][];
    };
    EnvironmentVariableView:
      | components["schemas"]["EnvironmentValueVariableView"]
      | components["schemas"]["EnvironmentSecretVariableView"]
      | components["schemas"]["EnvironmentAliasVariableView"]
      | components["schemas"]["EnvironmentUnsetVariableView"];
    EnvironmentValueVariableView: {
      variableId: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      /** @constant */
      kind: "value";
      value: string;
    };
    EnvironmentSecretVariableView: {
      variableId: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      /** @constant */
      kind: "secret";
      hasValue: boolean;
      secretVersion: number;
    };
    EnvironmentAliasVariableView: {
      variableId: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      /** @constant */
      kind: "alias";
      target: components["schemas"]["VariableName"];
    };
    EnvironmentUnsetVariableView: {
      variableId: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      /** @constant */
      kind: "unset";
    };
    /** @description Creates a variable when variableId is omitted or updates the identified variable without changing its existing kind. */
    EnvironmentVariableWrite:
      | components["schemas"]["EnvironmentValueVariableWrite"]
      | components["schemas"]["EnvironmentSecretVariableWrite"]
      | components["schemas"]["EnvironmentAliasVariableWrite"]
      | components["schemas"]["EnvironmentUnsetVariableWrite"];
    EnvironmentValueVariableWrite: {
      variableId?: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      /** @constant */
      kind: "value";
      value: string;
    };
    EnvironmentSecretVariableWrite: {
      variableId?: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      /** @constant */
      kind: "secret";
      value?: string;
      clearValue?: boolean;
    };
    EnvironmentAliasVariableWrite: {
      variableId?: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      /** @constant */
      kind: "alias";
      target: components["schemas"]["VariableName"];
    };
    EnvironmentUnsetVariableWrite: {
      variableId?: components["schemas"]["EnvironmentVariableId"];
      name: components["schemas"]["VariableName"];
      /** @constant */
      kind: "unset";
    };
    VariableName: string;
    EnvironmentView: {
      environmentId: components["schemas"]["EnvironmentId"];
      workspaceId: components["schemas"]["WorkspaceId"];
      name: string;
      revision: number;
      variables: components["schemas"]["EnvironmentVariableView"][];
    };
    CollectionView: {
      collectionId: components["schemas"]["CollectionId"];
      workspaceId: components["schemas"]["WorkspaceId"];
      parentCollectionId: components["schemas"]["CollectionId"] | null;
      name: string;
      headers: components["schemas"]["RequestField"][];
      /** @description Effective enabled headers after applying ancestor and local collection profiles. */
      effectiveHeaders: components["schemas"]["RequestField"][];
      revision: number;
    };
    RequestView: {
      requestId: components["schemas"]["RequestId"];
      workspaceId: components["schemas"]["WorkspaceId"];
      parentCollectionId: components["schemas"]["CollectionId"] | null;
      name: string;
      method: components["schemas"]["HttpMethod"];
      /** @constant */
      targetMode: "absolute";
      /** @description Absolute HTTP URL template validated after variable interpolation. */
      targetUrl: string;
      /** @constant */
      queryMode: "structured";
      query: components["schemas"]["RequestField"][];
      headers: components["schemas"]["RequestField"][];
      /** @description Effective enabled headers inherited from the request's collection ancestry before request-local overrides. */
      inheritedHeaders: components["schemas"]["RequestField"][];
      body: string;
      preRequestScript: string;
      postResponseScript: string;
      draftRevision: number;
    };
    ExecutionView: {
      executionId: components["schemas"]["ExecutionId"];
      requestId?: components["schemas"]["RequestId"];
      /** @enum {string} */
      state: "created" | "running" | "completed" | "failed";
      status?: number;
      headers?: components["schemas"]["HeaderField"][];
      bodyComplete: boolean;
      bodyBytes?: number;
      bodySha256?: string;
      bodyPreview?: string;
      bodyBlobId?: components["schemas"]["BlobId"];
      createdAt: components["schemas"]["UtcDateTime"];
      completedAt?: components["schemas"]["UtcDateTime"];
      error?: components["schemas"]["WebSocketError"];
      scriptLogs: components["schemas"]["ScriptLogEntry"][];
      scriptTests: components["schemas"]["ScriptTestResult"][];
      scriptError?: components["schemas"]["ScriptPhaseError"];
    };
    HeaderField: {
      name: string;
      value: string;
    };
    RequestExecutionInput: {
      method: components["schemas"]["HttpMethod"];
      /** @description Absolute HTTP URL template validated after variable interpolation. */
      targetUrl: string;
      query: components["schemas"]["RequestField"][];
      headers: components["schemas"]["RequestField"][];
      body: string;
      preRequestScript?: string;
      postResponseScript?: string;
    };
    ScriptLogEntry: {
      /** @description One-based production order across script logs and tests for this execution. */
      sequence: number;
      /** @enum {string} */
      phase: "pre-request" | "post-response";
      /** @enum {string} */
      level: "debug" | "info" | "warn" | "error";
      message: string;
      fields?: {
        [key: string]: string | number | boolean | null;
      };
    };
    ScriptTestResult: {
      /** @description One-based production order across script logs and tests for this execution. */
      sequence: number;
      name: string;
      /** @enum {string} */
      status: "passed" | "failed" | "errored";
      message?: string;
      /**
       * @description Stable localization key for an SDK-generated test message. Omitted for script-authored messages.
       * @enum {string}
       */
      messageCode?:
        | "assertion_expected_truthy"
        | "assertion_values_not_equal"
        | "assertion_values_not_deeply_equal"
        | "assertion_value_does_not_match"
        | "test_threw_non_error";
    };
    ScriptPhaseError: {
      /** @enum {string} */
      phase: "pre-request" | "post-response";
      code: string;
      message: string;
      line?: number;
      column?: number;
    };
    /** @enum {string} */
    HttpMethod:
      | "GET"
      | "POST"
      | "PUT"
      | "PATCH"
      | "DELETE"
      | "HEAD"
      | "OPTIONS";
    RequestField: {
      name: string;
      value: string;
      enabled: boolean;
    };
  };
  responses: {
    /** @description The request is invalid. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description Authentication is required or failed. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The current user is not allowed to perform this operation. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The requested resource does not exist or is not visible. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    ExecutionId: components["schemas"]["ExecutionId"];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getBackendHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backend health state. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackendHealth"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Authentication succeeded and a refresh cookie was set. */
      200: {
        headers: {
          /** @description Opaque rotating refresh credential in an HttpOnly cookie. */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessCredential"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
    };
  };
  refreshSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Refresh succeeded and the refresh cookie was rotated. */
      200: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessCredential"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked and refresh cookie cleared. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getCurrentSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current session. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentSession"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  downloadExecutionResponseBody: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exact response body bytes. */
      200: {
        headers: {
          "Content-Length"?: number;
          Digest?: string;
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  connectBackendWebSocket: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket protocol upgrade. */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
