/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Report backend liveness and readiness */
    get: operations["getBackendHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate with an enabled provider */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate a refresh credential and issue a new access token */
    post: operations["refreshSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the current session */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the current application session */
    get: operations["getCurrentSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/executions/{executionId}/body": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    /** Download exact stored response bytes */
    get: operations["downloadExecutionResponseBody"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Open the frontend control connection */
    get: operations["connectBackendWebSocket"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Format: uuid */
    UuidV7: string;
    /**
     * Format: date-time
     * @description Canonical RFC 3339 UTC timestamp with millisecond precision.
     * @example 2026-07-21T09:00:00.000Z
     */
    UtcDateTime: string;
    CorrelationId: components["schemas"]["UuidV7"];
    CommandId: components["schemas"]["UuidV7"];
    EventId: components["schemas"]["UuidV7"];
    UserId: components["schemas"]["UuidV7"];
    SessionId: components["schemas"]["UuidV7"];
    WorkspaceId: components["schemas"]["UuidV7"];
    CollectionId: components["schemas"]["UuidV7"];
    RequestId: components["schemas"]["UuidV7"];
    ExecutionId: components["schemas"]["UuidV7"];
    BlobId: components["schemas"]["UuidV7"];
    ProblemCode: string;
    ValidationError: {
      /** @description JSON Pointer to the invalid input. */
      path: string;
      code: components["schemas"]["ProblemCode"];
      message: string;
    };
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      code: components["schemas"]["ProblemCode"];
      detail: string;
      correlationId: components["schemas"]["CorrelationId"];
      errors: components["schemas"]["ValidationError"][];
    };
    BackendHealth: {
      /** @enum {string} */
      status: "ready" | "not_ready";
      version: string;
      checks: {
        [key: string]: "ready" | "not_ready";
      };
    };
    LoginRequest: {
      providerId: string;
      /** @description Provider-defined fields collected by the frontend. */
      fields: {
        [key: string]: string;
      };
    };
    AccessCredential: {
      accessToken: string;
      accessTokenExpiresAt: components["schemas"]["UtcDateTime"];
      session: components["schemas"]["CurrentSession"];
    };
    CurrentSession: {
      sessionId: components["schemas"]["SessionId"];
      user: components["schemas"]["CurrentUser"];
      createdAt: components["schemas"]["UtcDateTime"];
      absoluteExpiresAt: components["schemas"]["UtcDateTime"];
    };
    CurrentUser: {
      userId: components["schemas"]["UserId"];
      username: string;
      displayName: string;
    };
    WebSocketCommand:
      | components["schemas"]["SessionAuthenticateCommand"]
      | components["schemas"]["SystemPingCommand"]
      | components["schemas"]["WorkspaceListCommand"]
      | components["schemas"]["WorkspaceCreateCommand"]
      | components["schemas"]["TreeListCommand"]
      | components["schemas"]["CollectionCreateCommand"]
      | components["schemas"]["RequestCreateCommand"]
      | components["schemas"]["RequestGetCommand"]
      | components["schemas"]["RequestUpdateCommand"]
      | components["schemas"]["ExecutionStartCommand"];
    CommandEnvelope: {
      /** @constant */
      protocolVersion: 1;
      /** @constant */
      kind: "command";
      id: components["schemas"]["CommandId"];
      type: string;
      payload: Record<string, never>;
    };
    SessionAuthenticateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "session.authenticate";
      payload?: {
        accessToken: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "SessionAuthenticateCommand";
    };
    SystemPingCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "system.ping";
      payload?: Record<string, never>;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "SystemPingCommand";
    };
    WorkspaceListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.list";
      payload?: Record<string, never>;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceListCommand";
    };
    WorkspaceCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "workspace.create";
      payload?: {
        name: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "WorkspaceCreateCommand";
    };
    TreeListCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "tree.list";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "TreeListCommand";
    };
    CollectionCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "collection.create";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        name: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "CollectionCreateCommand";
    };
    RequestCreateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.create";
      payload?: {
        workspaceId: components["schemas"]["WorkspaceId"];
        parentCollectionId: components["schemas"]["CollectionId"] | null;
        name: string;
        /** Format: uri */
        targetUrl: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestCreateCommand";
    };
    RequestGetCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.get";
      payload?: {
        requestId: components["schemas"]["RequestId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestGetCommand";
    };
    RequestUpdateCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "request.update";
      payload?: {
        requestId: components["schemas"]["RequestId"];
        expectedDraftRevision: number;
        name: string;
        /** Format: uri */
        targetUrl: string;
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "RequestUpdateCommand";
    };
    ExecutionStartCommand: components["schemas"]["CommandEnvelope"] & {
      /** @constant */
      type?: "execution.start";
      payload?: {
        requestId: components["schemas"]["RequestId"];
      };
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "ExecutionStartCommand";
    };
    WebSocketReply: {
      /** @constant */
      protocolVersion: 1;
      /** @constant */
      kind: "reply";
      commandId: components["schemas"]["CommandId"];
      /** @enum {string} */
      outcome: "success" | "error";
      correlationId: components["schemas"]["CorrelationId"];
      payload?: unknown;
      error?: components["schemas"]["WebSocketError"];
    };
    WebSocketError: {
      code: components["schemas"]["ProblemCode"];
      message: string;
      errors: components["schemas"]["ValidationError"][];
    };
    WebSocketEvent: {
      /** @constant */
      protocolVersion: 1;
      /** @constant */
      kind: "event";
      id: components["schemas"]["EventId"];
      type: string;
      occurredAt: components["schemas"]["UtcDateTime"];
      correlationId: components["schemas"]["CorrelationId"];
      payload: unknown;
    };
    WorkspaceSummary: {
      workspaceId: components["schemas"]["WorkspaceId"];
      name: string;
      /** @enum {string} */
      role: "owner" | "editor" | "viewer";
    };
    TreeNode: {
      nodeId: components["schemas"]["UuidV7"];
      /** @enum {string} */
      kind: "collection" | "request";
      name: string;
      position: number;
    };
    RequestView: {
      requestId: components["schemas"]["RequestId"];
      workspaceId: components["schemas"]["WorkspaceId"];
      name: string;
      /** @constant */
      method: "GET";
      /** @constant */
      targetMode: "absolute";
      /** Format: uri */
      targetUrl: string;
      /** @constant */
      queryMode: "structured";
      draftRevision: number;
    };
    ExecutionView: {
      executionId: components["schemas"]["ExecutionId"];
      requestId: components["schemas"]["RequestId"];
      /** @enum {string} */
      state: "created" | "running" | "completed" | "failed";
      status?: number;
      headers?: components["schemas"]["HeaderField"][];
      bodyComplete: boolean;
      bodyBytes?: number;
      bodySha256?: string;
      bodyPreview?: string;
      bodyBlobId?: components["schemas"]["BlobId"];
      createdAt: components["schemas"]["UtcDateTime"];
      completedAt?: components["schemas"]["UtcDateTime"];
      error?: components["schemas"]["WebSocketError"];
    };
    HeaderField: {
      name: string;
      value: string;
    };
  };
  responses: {
    /** @description The request is invalid. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description Authentication is required or failed. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The current user is not allowed to perform this operation. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The requested resource does not exist or is not visible. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    ExecutionId: components["schemas"]["ExecutionId"];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getBackendHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backend health state. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackendHealth"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Authentication succeeded and a refresh cookie was set. */
      200: {
        headers: {
          /** @description Opaque rotating refresh credential in an HttpOnly cookie. */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessCredential"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
    };
  };
  refreshSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Refresh succeeded and the refresh cookie was rotated. */
      200: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessCredential"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked and refresh cookie cleared. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getCurrentSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current session. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentSession"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  downloadExecutionResponseBody: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Exact response body bytes. */
      200: {
        headers: {
          "Content-Length"?: number;
          Digest?: string;
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  connectBackendWebSocket: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket protocol upgrade. */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
