/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get proxy readiness
     * @description Returns only readiness and version information suitable for container and service health checks. It does not expose configuration, limits, or principal information.
     */
    get: operations["getProxyHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get proxy capabilities and principal limits
     * @description Returns protocol support and effective limits for the authenticated backend principal. The backend must verify API and frame compatibility before creating executions.
     */
    get: operations["getProxyCapabilities"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/executions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an HTTP execution session
     * @description Creates a transient execution owned by the authenticated backend principal. Ownership is derived exclusively from the bearer token and cannot be supplied or changed by the client. Idempotency keys are scoped to the principal and retained until the execution is released or expires.
     */
    post: operations["createProxyExecution"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/executions/{executionId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Opaque identifier of a transient proxy execution. */
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    /**
     * Get execution state
     * @description Returns current control-plane state for an execution owned by the authenticated principal. A missing execution and an execution owned by another principal both return 404.
     */
    get: operations["getProxyExecution"];
    put?: never;
    post?: never;
    /**
     * Release a terminal execution
     * @description Acknowledges that the backend has persisted or discarded the result and releases the execution, its response cache, and its idempotency-key mapping. Active executions cannot be released and must be cancelled first.
     */
    delete: operations["releaseProxyExecution"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/executions/{executionId}/request-body": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Opaque identifier of a transient proxy execution. */
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Stream the target request body
     * @description Streams the target request payload as unmodified bytes. This operation is valid only for an execution created with body mode `stream` and while that execution is accepting an upload. The authenticated principal must own the execution. The protocol content type does not replace or imply the target request's Content-Type header. Request upload resume is not supported in framing version 1; an interrupted upload fails the execution.
     */
    put: operations["uploadProxyExecutionRequestBody"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/executions/{executionId}/response": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Opaque identifier of a transient proxy execution. */
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    /**
     * Stream the target response
     * @description Opens the response data plane for an execution owned by the authenticated principal. Only one response reader may be active for an execution; a second reader receives 409 until the first stream completes or disconnects. The proxy returns a framed binary stream and may send heartbeat frames while waiting for the target. A RESPONSE_HEAD frame announces the target response before any BODY frame. The outer HTTP status describes this proxy operation; every valid target HTTP status, including 4xx and 5xx, is carried in RESPONSE_HEAD and completes normally unless a separate network or protocol failure occurs. Cached frames remain available until the terminal execution is released or expires.
     */
    get: operations["streamProxyExecutionResponse"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/executions/{executionId}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Opaque identifier of a transient proxy execution. */
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel an execution
     * @description Requests best-effort cancellation of request upload, target communication, response streaming, and transient caching for an execution owned by the authenticated principal. Cancellation cannot guarantee that the target did not already process some or all of the request. Repeated cancellation requests are idempotent and return the current session state.
     */
    post: operations["cancelProxyExecution"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      /** @enum {string} */
      status: "ready" | "not_ready";
      /** @constant */
      apiVersion: "0.1.1";
      /** @description Version of the running proxy implementation. */
      componentVersion: string;
    };
    Capabilities: {
      /** @constant */
      apiVersion: "0.1.1";
      responseFrameVersions: 1[];
      outboundHttpVersions: "HTTP/1.1"[];
      features: components["schemas"]["CapabilityFeatures"];
      limits: components["schemas"]["CapabilityLimits"];
    };
    CapabilityFeatures: {
      /** @constant */
      responseResume: true;
      /** @constant */
      requestUploadResume: false;
      redirectModes: ["manual"];
      tlsVerificationModes: ("strict" | "insecure")[];
      transportMetadata: components["schemas"]["TransportMetadataCapabilities"];
      /** @constant */
      automaticContentDecompression: false;
      /** @constant */
      cookieJar: false;
    };
    /** @description Transport observations available to the authenticated principal. A true value indicates implementation and policy support; an observation may still be absent when a particular connection fails before the value is known. */
    TransportMetadataCapabilities: {
      remoteEndpoint: boolean;
      localEndpoint: boolean;
      connectionReuse: boolean;
      tlsSummary: boolean;
      peerCertificateChain: boolean;
    };
    CapabilityLimits: {
      maxMetadataBytes: number;
      maxRequestHeaderCount: number;
      maxRequestBodyBytes: number;
      maxResponseBodyBytes: number;
      maxCacheBytesPerPrincipal: number;
      maxConcurrentExecutionsPerPrincipal: number;
      responseCacheRetentionMs: number;
      /** @constant */
      maxFramePayloadBytes: 1048576;
    };
    /** @description Opaque execution identifier. Clients must not infer ownership or other semantics from its value. */
    ExecutionId: string;
    CreateExecutionRequest: {
      request: components["schemas"]["TargetRequest"];
    };
    TargetRequest: {
      /** @description Final HTTP method token to send to the target. */
      method: string;
      /**
       * Format: uri
       * @description Final semantic absolute HTTP or HTTPS URL, including the already-materialized path and query string. The proxy must not independently add, remove, or reorder query parameters. The Host header and TLS server name are derived from this URL. URI fragments and user information are not permitted.
       */
      url: string;
      /** @description Ordered final target header fields. Duplicate names are permitted. Header names are compared case-insensitively against the forbidden list. */
      headers: components["schemas"]["HeaderField"][];
      body: components["schemas"]["RequestBodyDescriptor"];
      behavior: components["schemas"]["ExecutionBehavior"];
    };
    HeaderField: {
      name: string;
      /** @description Unmodified semantic header value. Control characters prohibited by HTTP/1.1 are not permitted. */
      value: string;
    };
    RequestBodyDescriptor: {
      /** @enum {string} */
      mode: "none" | "stream";
      /** @description Exact raw body length when known, otherwise null. Must be zero when mode is none. The proxy derives Content-Length from a known value and otherwise selects HTTP/1.1 streaming transfer framing. */
      length: number | null;
      /** @description Lowercase SHA-256 digest of the complete raw body when known, otherwise null. Must be null when mode is none. Because the proxy streams to the target, a mismatch can be detected only after some or all bytes have reached the target. */
      sha256: string | null;
    } & unknown;
    /** @description Non-header target behavior. Outbound HTTP is HTTP/1.1, cookies are not retained between executions, and content encoding is never automatically decompressed. Transfer coding may be removed by HTTP framing while content-encoded bytes remain unchanged. */
    ExecutionBehavior: {
      connectTimeoutMs: number;
      responseHeaderTimeoutMs: number;
      /** @description Maximum time between bytes received from the target after its response begins. */
      responseIdleTimeoutMs: number;
      /** @description Maximum lifetime from execution creation through target completion. Starting at creation also bounds sessions that never begin request-body upload. */
      totalTimeoutMs: number;
      /**
       * @description Redirect responses are returned to the backend and are never followed automatically in the MVP.
       * @constant
       */
      redirectMode: "manual";
      /**
       * @description Strict verifies the target certificate and hostname. Insecure explicitly disables enforcement of both checks for this execution while retaining TLS encryption. The proxy reports the verification outcome in transport metadata when its transport implementation exposes it.
       * @enum {string}
       */
      tlsVerification: "strict" | "insecure";
      /** @description Maximum target response body accepted for this execution. It must not exceed the effective principal capability. */
      maxResponseBodyBytes: number;
    };
    /** @description Transient execution state. Principal identity is intentionally omitted because ownership is derived from authentication and is not client-controlled. */
    ExecutionSession: {
      executionId: components["schemas"]["ExecutionId"];
      state: components["schemas"]["ExecutionState"];
      requestBodyState: components["schemas"]["RequestBodyState"];
      responseState: components["schemas"]["ResponseState"];
      /** Format: date-time */
      createdAt: string;
      /**
       * Format: date-time
       * @description Null while the execution is active. After a terminal state, the time at which the proxy may delete transient state, cached frames, and the idempotency-key mapping.
       */
      expiresAt: string | null;
      /** @description Safe terminal failure details. Null unless state is failed. */
      error: components["schemas"]["ExecutionStreamError"] | null;
    };
    /** @enum {string} */
    ExecutionState:
      | "accepted"
      | "active"
      | "cancelling"
      | "completed"
      | "failed"
      | "cancelled"
      | "expired";
    /** @enum {string} */
    RequestBodyState:
      | "not_required"
      | "awaiting_upload"
      | "streaming"
      | "complete"
      | "failed"
      | "cancelled";
    /** @enum {string} */
    ResponseState:
      | "waiting"
      | "streaming"
      | "complete"
      | "failed"
      | "cancelled"
      | "expired";
    /**
     * Format: binary
     * @description Version 1 APInteract framed response stream. Each frame starts with the 16-byte header defined by the media type's x-apinteract-framing contract, followed by exactly payloadLength bytes.
     */
    ProxyResponseStream: string;
    /** @description Target response metadata. Transport observations are emitted here before response body frames when they are available. */
    ResponseHead: {
      /** @description Final target HTTP response status. */
      status: number;
      reasonPhrase?: string | null;
      /**
       * @description HTTP transport version negotiated with the target.
       * @enum {string}
       */
      httpVersion: "HTTP/1.1";
      headers: components["schemas"]["HeaderList"];
      /**
       * Format: date-time
       * @description Time at which the proxy received the final target response headers.
       */
      receivedAt: string;
      transport?: components["schemas"]["TransportObservation"];
    };
    ResponseTrailers: {
      headers: components["schemas"]["HeaderList"];
    };
    ResponseComplete: {
      bodyBytes: number;
      /** @description Lowercase SHA-256 digest of the complete raw response body when calculated. */
      bodySha256: string | null;
      timings: components["schemas"]["ExecutionTimings"];
      /** Format: date-time */
      completedAt: string;
    };
    /** @description Target execution timings measured by the proxy. Optional phases are omitted when they do not apply or cannot be measured. */
    ExecutionTimings: {
      dnsMs?: number;
      connectMs?: number;
      tlsMs?: number;
      firstByteMs?: number;
      totalMs: number;
    };
    /** @description Best available observations about the target transport connection. Fields are omitted when they do not apply, are unavailable from the transport implementation, are suppressed by proxy policy, or were not observed before failure. */
    TransportObservation: {
      localEndpoint?: components["schemas"]["NetworkEndpoint"];
      remoteEndpoint?: components["schemas"]["NetworkEndpoint"];
      /** @description Whether the target connection existed before this execution. */
      connectionReused?: boolean;
      tls?: components["schemas"]["TlsObservation"];
    };
    /** @description Observed socket endpoint. The remote endpoint is the address actually connected after name resolution, not the target hostname. */
    NetworkEndpoint:
      | {
          /** Format: ipv4 */
          address: string;
          port: number;
          /** @constant */
          family: "ipv4";
        }
      | {
          /** Format: ipv6 */
          address: string;
          port: number;
          /** @constant */
          family: "ipv6";
        };
    /** @description TLS observations collected during connection establishment. On a failed handshake, only values observed before failure are present. */
    TlsObservation: {
      /** @enum {string} */
      verificationMode: "strict" | "insecure";
      /** @description Whether the observed peer certificate and hostname satisfied normal strict verification, including when insecure mode allowed the connection to continue. */
      authorized?: boolean;
      authorizationErrorCode?: components["schemas"]["TlsAuthorizationErrorCode"];
      /** @enum {string} */
      protocol?: "TLSv1.2" | "TLSv1.3";
      /**
       * @description Negotiated ALPN protocol, or null when the peer did not negotiate ALPN.
       * @enum {string|null}
       */
      alpnProtocol?: "http/1.1" | null;
      /** @description TLS Server Name Indication value sent to the target, or null when no server name was sent. */
      serverName?: string | null;
      cipher?: components["schemas"]["TlsCipher"];
      /** @description Peer certificate chain in leaf-first order as exposed by the transport runtime. A self-signed peer normally produces one entry. */
      peerCertificateChain?: components["schemas"]["TlsPeerCertificate"][];
    };
    /**
     * @description Normalized primary reason that normal strict certificate or hostname verification did not authorize the peer.
     * @enum {string}
     */
    TlsAuthorizationErrorCode:
      | "self_signed_certificate"
      | "unknown_certificate_authority"
      | "hostname_mismatch"
      | "certificate_expired"
      | "certificate_not_yet_valid"
      | "certificate_revoked"
      | "invalid_certificate_chain"
      | "unsupported_certificate"
      | "other_verification_error";
    TlsCipher: {
      /** @description Cipher suite name reported by the transport runtime. */
      name: string;
      /** @description IANA cipher suite name when the transport runtime provides it. */
      standardName?: string | null;
    };
    TlsPeerCertificate: {
      /** @description Base64 representation of the exact DER certificate bytes exposed by the transport runtime. */
      derBase64: string;
      /** @description Lowercase SHA-256 digest of the DER certificate bytes. */
      sha256Fingerprint: string;
    };
    /** @description Terminal execution failure. Valid target HTTP status responses, including 4xx and 5xx, are not failures. */
    ExecutionStreamError: {
      /**
       * @description Origin of the execution failure. Valid target HTTP status responses, including 4xx and 5xx, are not errors.
       * @enum {string}
       */
      category: "proxy" | "network" | "http_protocol";
      /** @description Stable snake_case machine-readable error code. Clients must tolerate codes added in compatible API revisions. */
      code: string;
      /** @description Safe human-readable message that does not expose secrets or internal stack traces. */
      message: string;
      /** @enum {string} */
      phase:
        | "upload"
        | "dns"
        | "connect"
        | "tls"
        | "request"
        | "response"
        | "cache"
        | "internal";
      retryable: boolean;
      /** @description Transport observations available before failure. When a response head was already emitted, the backend retains the observations from that frame and this field may be omitted. */
      transport?: components["schemas"]["TransportObservation"];
    };
    /** @description Ordered HTTP header fields. Duplicate names are preserved. */
    HeaderList: components["schemas"]["HeaderField"][];
    /** @description RFC 9457 problem details with a stable APInteract error code. Extension members are permitted. */
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      /** @constant */
      category: "proxy";
      detail?: string;
      /** Format: uri-reference */
      instance?: string;
      /** @description Stable snake_case machine-readable error code. */
      code: string;
      /** @description Opaque identifier suitable for correlating sanitized proxy logs. */
      traceId?: string;
    };
  };
  responses: {
    /** @description The request does not satisfy the proxy protocol. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The bearer token is missing, invalid, or expired. */
    Unauthorized: {
      headers: {
        /** @example Bearer */
        "WWW-Authenticate"?: string;
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The execution does not exist or is owned by another authenticated principal. */
    ExecutionNotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The operation is not valid in the execution's current state. */
    ExecutionStateConflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The idempotency key was previously used by this principal with a different execution descriptor. */
    IdempotencyConflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The execution existed for this principal, but its transient response data is no longer available. The proxy retains only an owner-scoped in-memory tombstone for one additional configured response-cache retention window, subject to a bounded process-wide capacity. Missing, foreign, explicitly released, and tombstone-evicted executions remain indistinguishable as not found. */
    ExecutionExpired: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The requested frame sequence is outside the cached response stream. */
    SequenceNotSatisfiable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The request exceeds a configured metadata, body, or cache limit. */
    PayloadTooLarge: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The streamed body does not match declared length or digest metadata. */
    UnprocessableContent: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The authenticated principal has exceeded a configured execution or transfer limit. */
    TooManyRequests: {
      headers: {
        /** @description Seconds before another attempt should be made. */
        "Retry-After"?: number;
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The proxy cannot accept another execution. */
    ServiceUnavailable: {
      headers: {
        /** @description Seconds before another attempt should be made. */
        "Retry-After"?: number;
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    /** @description Opaque caller-generated key scoped to the authenticated principal. Concurrent or repeated creation requests with the same key and identical descriptor resolve to one execution. Reuse with different content returns 409. */
    IdempotencyKey: string;
    /** @description Opaque identifier of a transient proxy execution. */
    ExecutionId: components["schemas"]["ExecutionId"];
    /** @description Resume after this previously received frame sequence. When omitted, the stream starts or replays from sequence zero. */
    AfterSequence: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getProxyHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The proxy is ready to accept control-plane requests. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      /** @description The process is running but the proxy is not ready. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  getProxyCapabilities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Capabilities and effective limits. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Capabilities"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  createProxyExecution: {
    parameters: {
      query?: never;
      header: {
        /** @description Opaque caller-generated key scoped to the authenticated principal. Concurrent or repeated creation requests with the same key and identical descriptor resolve to one execution. Reuse with different content returns 409. */
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateExecutionRequest"];
      };
    };
    responses: {
      /** @description Execution session created, or the original creation result replayed for the same principal, idempotency key, and request descriptor. */
      201: {
        headers: {
          /** @description Relative or absolute URL of the created execution. */
          Location?: string;
          /** @description True when this response replays an execution created by an earlier request with the same idempotency key. */
          "Idempotency-Replayed"?: boolean;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionSession"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      409: components["responses"]["IdempotencyConflict"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["TooManyRequests"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  getProxyExecution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Opaque identifier of a transient proxy execution. */
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current execution state. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionSession"];
        };
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["ExecutionNotFound"];
    };
  };
  releaseProxyExecution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Opaque identifier of a transient proxy execution. */
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The terminal execution and its transient data were released. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["ExecutionNotFound"];
      409: components["responses"]["ExecutionStateConflict"];
    };
  };
  uploadProxyExecutionRequestBody: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Opaque identifier of a transient proxy execution. */
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": string;
      };
    };
    responses: {
      /** @description The complete request body was accepted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["ExecutionNotFound"];
      409: components["responses"]["ExecutionStateConflict"];
      413: components["responses"]["PayloadTooLarge"];
      422: components["responses"]["UnprocessableContent"];
    };
  };
  streamProxyExecutionResponse: {
    parameters: {
      query?: {
        /** @description Resume after this previously received frame sequence. When omitted, the stream starts or replays from sequence zero. */
        afterSequence?: components["parameters"]["AfterSequence"];
      };
      header?: never;
      path: {
        /** @description Opaque identifier of a transient proxy execution. */
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Framed target response stream. A terminal COMPLETE or ERROR frame is required; connection closure alone does not indicate successful completion. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/vnd.apinteract.proxy-stream": components["schemas"]["ProxyResponseStream"];
        };
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["ExecutionNotFound"];
      409: components["responses"]["ExecutionStateConflict"];
      410: components["responses"]["ExecutionExpired"];
      416: components["responses"]["SequenceNotSatisfiable"];
    };
  };
  cancelProxyExecution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Opaque identifier of a transient proxy execution. */
        executionId: components["parameters"]["ExecutionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The execution was already terminal and its state was unchanged. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionSession"];
        };
      };
      /** @description Cancellation was accepted or had already been requested. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionSession"];
        };
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["ExecutionNotFound"];
    };
  };
}
